version: "2"
#
# Services
#
services:

  arangodb:
       image: arangodb/arangodb:3.2.3
       ports:
          - 8529:8529
       environment:
          - ARANGO_ROOT_PASSWORD=openSesame
       networks:
          - localnet

# Networks
#
networks:
  localnet:
    # driver: bridge
    external: true