---
smtpHost: mail.lightapi.net
port:587
fromEmail: noreply@lightapi.net
subject: New User Initial confirmation email
emitEvent: false
content: Welcome to Light-portal! <br/><br/> To complete your account registration, please confirm your email address by clicking on the following link:<br/><br/>{}<br/><br/>If you cannot click on the link above, please copy and paste it into your web browser.<br/>Please visit http://www.fongo.com for more information.
serverHost: http://localhost:8080/user/token/
password: change-To-Real-Password
